apiVersion: v1
kind: Service
metadata:
  name: plantcare-chatbot-service
spec:
  selector:
    app: plantcare-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # change to NodePort if needed
